apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: testservice
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_DEFAULT_REPLICATION_FACTOR: "1"
  KAFKA_MIN_INSYNC_REPLICAS: "1"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_LISTENERS: "INTERNAL://:9092,EXTERNAL://:29092"
  KAFKA_ADVERTISED_LISTENERS: "INTERNAL://testservice-kafka:9092,EXTERNAL://localhost:29092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"