apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: testservice
data:
  KAFKA_BOOTSTRAP_SERVERS: "testservice-kafka:9092"
  REDIS_HOST: "testservice-redis"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/testservice_db"
  POSTGRES_DB: "testservice_db"