apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: testservice
data:
  SPRING_PROFILES_ACTIVE: "docker"
  KAFKA_BOOTSTRAP_SERVERS: "testservice-kafka:9092"
  REDIS_HOST: "testservice-redis"