apiVersion: v1
kind: Service
metadata:
  name: testservice-app
  namespace: testservice
spec:
  selector:
    app: testservice-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer  # Для доступа снаружи