apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: testservice
type: Opaque
data:
  PG_USERNAME: dXVzZXI=          # echo -n "uuser" | base64
  PG_PASSWORD: cHBhc3N3b3Jk      # echo -n "ppassword" | base64