apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: testservice
type: Opaque
data:
  username: dXVzZXI=          # echo -n "uuser" | base64
  password: cHBhc3N3b3Jk      # echo -n "ppassword" | base64