spring:
  datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
        username: ${SPRING_DATASOURCE_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_PASSWORD:password}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: "1111"
