spring:
  cloud:
    kubernetes:
      config:
        enabled: true
        name: test-service
        namespace: testservice

  datasource:
    url: "jdbc:postgresql://postgres:5432/testservice_db"

  kafka:
    bootstrap-servers: "kafka-service:9092"

  data:
    redis:
      host: "redis"

cache:
  ttl: 86400  # 60*60*24 = 86400 sec