spring:
  application:
    name: test.service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: testservice-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: ru.bellintegrator.test.service.dto.UserEventDto

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    template:
      default-topic: user-topic

  jpa:
    hibernate:
      ddl-auto: create-drop  # создаёт схему и удаляет её при остановке приложения.
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      password: "1111"

#  logging:
#    level:
##      ru.bellintegrator.test.service: "debug"
##      org.springframework.web: DEBUG
#      root: "debug"
#      org.springframework.web: "debug"

#    pattern:
#      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

cache:
  ttl: 86400  # 60*60*24 = 86400 sec