spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/testservice_db"
    username: "uuser"
    password: "ppassword"

  kafka:
    bootstrap-servers: "localhost:9092"
    admin:
      properties:
        bootstrap.servers: localhost:9092
        client.id: test-service-admin
        request.timeout.ms: 5000
        connection.timeout.ms: 3000

  data:
    redis:
      host: localhost

cache:
  ttl: 30