spring:
  application:
    name: test-service

  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: create-drop  # создаёт схему и удаляет её при остановке приложения.
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        globally_quoted_identifiers: true

  data:
    redis:
      port: 6379
      password: "1111"
cache:
  ttl: 86400  # 60*60*24 = 86400 sec


app:
  kafka:
    log-topic: "log-topic"