spring:
  application:
    name: test-service

  main:
    allow-bean-definition-overriding: true

#  kafka:
#    consumer:
#      group-id: testservice-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: ru.bellintegrator.test.service.dto.UserEventDto

#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: false
#    template:
#      default-topic: user-topic

  jpa:
    hibernate:
      ddl-auto: create-drop  # создаёт схему и удаляет её при остановке приложения.
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        globally_quoted_identifiers: true

  data:
    redis:
      port: 6379
      password: "1111"
cache:
  ttl: 86400  # 60*60*24 = 86400 sec


app:
  kafka:
    log-topic: "log-topic"